easy_admin:
    site_name: 'Admin Interface'
    design:
        menu:
            - {label: "Entities"}
            - label: "Posts"
              children:
                  - {entity: Post, label: "Posts list", icon: "th-list"}
                  - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}}
            - label: "Category"
              children:
                  - {entity: Category, label: "List of categories", icon: "th-list"}
                  - {entity: Category, label: "Add category", icon: "plus", params: {action: 'new'}}
            - label: "Tags"
              children:
                  - {entity: Tag, label: "List of tags", icon: "th-list"}
                  - {entity: Tag, label: "Add tag", icon: "plus", params: {action: 'new'}}
            - {label: "Settings"}
            - {entity: User, icon: "user", permission: ['ROLE_ADMIN']}
    entities:
        Post:
            controller: App\Controller\PostController
            class: App\Entity\Post
            label: "Post"
            form:
                fields:
                    - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-12'}
                    - title
                    - {property: 'content', type: 'text_editor'}
                    - createdAt
                    - published
                    - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-12'}
                    - category
                    - tags
                    - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-12'}
                    - {property: 'thumbnailFile', type: 'vich_image'}
                    - {property: 'attachments', type: 'collection', type_options: {entry_type: 'App\Form\AttachmentType', by_reference: false}}
            list:
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
                title: "Amazing posts here !"
                filters: ['published']
                fields:
                    - title
                    - content
                    - createdAt
                    - tags
                    - category
                    - {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}

            show:
                fields:
                    - title
                    - {property: 'content', type: 'raw'}
                    - createdAt
                    - published
                    - tags
                    - {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}
                    - {property: 'attachments', template: 'images.html.twig'}
            edit:
                help: Edit fields

        Category:
            class: App\Entity\Category
            list:
                fields:
                    - title
                    - slug
                    - posts
        Tag:
            class: App\Entity\Tag
            form:
                fields:
                    - name
                    - slug
        User:
            class: App\Entity\User
            item_permission: 'ROLE_ADMIN'
            list:
                fields:
                    - email
                    - roles
        # List the entity class name you want to manage



