easy_admin:
    site_name: 'Admin Interface'
    design:
        menu:
            - {label: "Entities"}
            - label: "Posts"
              children:
                  - {entity: Post, label: "Posts list", icon: "th-list"}
                  - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}}
            - label: "Category"
              children:
                  - {entity: Category, label: "List of categories", icon: "th-list"}
                  - {entity: Category, label: "Add category", icon: "plus", params: {action: 'new'}}
            - label: "Tags"
              children:
                  - {entity: Tag, label: "List of tags", icon: "th-list"}
                  - {entity: Tag, label: "Add tag", icon: "plus", params: {action: 'new'}}
            - {label: "Settings"}
            - {entity: User, icon: "user"}
    entities:
        Post:
            class: App\Entity\Post
            label: "Post"
            form:
                fields:
                    - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-12'}
                    - title
                    - {property: 'content', type: 'text_editor'}
                    - createdAt
                    - published
                    - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-12'}
                    - category
                    - tags
            list:
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
                title: "Amazing posts here !"
                filters: ['published']
            show:
                fields:
                    - title
                    - {property: 'content', type: 'raw'}
                    - createdAt
                    - published
            edit:
                help: Edit fields
                fields:
                    - '-tags'
        Category:
            class: App\Entity\Category
        Tag:
            class: App\Entity\Tag
            form:
                fields:
                    - name
                    - slug
        User:
            class: App\Entity\User

        # List the entity class name you want to manage



